export const UPDATE_INITIAL_DATA = 'UPDATE_INITIAL_DATA'
export const HANDLE_ERROR_STATUS = 'HANDLE_ERROR_STATUS'
export const UPDATE_FORM_ANSWER = 'UPDATE_FORM_ANSWER'
export const CLEAR_FORM_ANSWERS = 'CLEAR_FORM_ANSWERS'